/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.gravitino.rest.v1.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import javax.annotation.Nullable;

/** A table column in the public Gravitino V1 wire contract. */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = false)
public final class Column {

  @JsonProperty(value = "name", required = true)
  private final String name;

  @JsonProperty(value = "type", required = true)
  private final DataType type;

  @Nullable
  @JsonProperty("comment")
  private final String comment;

  @JsonProperty(value = "nullable", required = true)
  private final boolean nullable;

  @JsonProperty(value = "autoIncrement", required = true)
  private final boolean autoIncrement;

  @Nullable
  @JsonProperty("defaultValue")
  private final ValueExpression defaultValue;

  /**
   * Creates a table column.
   *
   * @param name column name.
   * @param type column data type.
   * @param comment optional column comment.
   * @param nullable whether the column may contain null.
   * @param autoIncrement whether the column is generated by auto increment.
   * @param defaultValue optional default expression.
   */
  @JsonCreator
  public Column(
      @JsonProperty(value = "name", required = true) String name,
      @JsonProperty(value = "type", required = true) DataType type,
      @Nullable @JsonProperty("comment") String comment,
      @JsonProperty(value = "nullable", required = true) boolean nullable,
      @JsonProperty(value = "autoIncrement", required = true) boolean autoIncrement,
      @Nullable @JsonProperty("defaultValue") ValueExpression defaultValue) {
    this.name = ModelSupport.requireNonEmpty(name, "name");
    this.type = Objects.requireNonNull(type, "type cannot be null");
    this.comment = comment;
    this.nullable = nullable;
    this.autoIncrement = autoIncrement;
    this.defaultValue = defaultValue;
  }

  /**
   * @return column name.
   */
  public String getName() {
    return name;
  }

  /**
   * @return column data type.
   */
  public DataType getType() {
    return type;
  }

  /**
   * @return optional column comment.
   */
  @Nullable
  public String getComment() {
    return comment;
  }

  /**
   * @return whether the column may contain null.
   */
  public boolean isNullable() {
    return nullable;
  }

  /**
   * @return whether the column is generated by auto increment.
   */
  public boolean isAutoIncrement() {
    return autoIncrement;
  }

  /**
   * @return optional default expression.
   */
  @Nullable
  public ValueExpression getDefaultValue() {
    return defaultValue;
  }
}
