#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM eclipse-temurin:17.0.16_8-jre-jammy AS java17

FROM apache/spark:3.5.3

USER root

COPY --from=java17 /opt/java/openjdk /opt/java/openjdk17

RUN mkdir -p /opt/spark/conf /opt/spark/work-dir \
    && chown -R 185:185 /opt/spark/conf /opt/spark/work-dir

COPY --chown=185:185 build/spark/*.jar /opt/spark/jars/
COPY --chown=185:185 spark-defaults.conf /opt/spark/conf/spark-defaults.conf

ENV JAVA_HOME=/opt/java/openjdk17
ENV PATH=/opt/java/openjdk17/bin:${PATH}

USER 185

WORKDIR /opt/spark/work-dir
